sudo: required
services:
  - docker

before_install:
  - docker build -t jlgoh/react-test -f ./client/Dockerfile.dev ./client
  #Enter other installation of test environments for e.g. server, worker

script:
  - docker run -e CI=true jlgoh/react-test npm run test
  #Enter other installation of test scripts for e.g. server, worker

after_success:
  - docker build -t jlgoh/multi-client ./client
  - docker build -t jlgoh/multi-nginx ./nginx
  - docker build -t jlgoh/multi-server ./server
  - docker build -t jlgoh/multi-worker ./worker

  #Login to CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to Docker Hub
  - docker push jlgoh/multi-client
  - docker push jlgoh/multi-nginx
  - docker push jlgoh/multi-server
  - docker push jlgoh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-269630046698
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
